### ISSUE TITLE
The training stop with ResourceExhaustedError

### ISSUE THREAD

**Issue by JM-IP** [larq/larq#173]
I used 4 gpus (GTX1080TI) to train the birealnet, after about 50 epoches, it occur ResourceExhaustedError.
I use 512 as the batchsize as default.
If yo need more information, we can have more discussions.
Could you help to solve this error?

**Comment by JM-IP** [comment]
I believe it's the same error you need here [(https://github.com/tensorflow/tensorflow/issues/29213)].

**Comment by lgeiger** [comment]
We saw this error a while back, and it wasn't related to Larq. `.prefetch(tf.data.experimental.AUTOTUNE)` interacted with our misconfigured Kubernetes pod in a bad way. Since then we have resolved this problem in the latest version of `zookeeper`.

Are you still seeing this problem with `larq@0.6.0`, `larq-zoo@0.3.0`, `zookeeper@0.4.1` and `tensorflow_datasets@1.1.0`?

Also make sure not to use the `--data-cache memory` option if you don't have 200+GB of memory. You can also try imagenet `--dataset-version 5.0.0` which includes some experimental optimizations that reduce CPU and memory usage and should speed up training.

**Comment by JM-IP** [comment]
Would you like to tell me what does it matter using different dataset-version?

**Comment by lgeiger** [comment]
TensorFlow Datasets can include multiple versions of the same dataset which might have slight differences, or in the case of ImageNet will use a different code path: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/imagenet.py#L93-L108

For more info on the dataset versions take a look at: https://github.com/tensorflow/datasets/blob/master/docs/datasets_versioning.md

**Comment by appleleaves** [comment]
I used the download dir and its contains to generate the 5.0.0 version of imagenet2012,
it stops with the below information:
" supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-08 15:50:04.220786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-08-08 15:50:08.857528: W tensorflow/compiler/xla/service/platform_util.cc:256] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
2019-08-08 15:50:08.857528: W tensorflow/compiler/xla/service/platform_util.cc:256] unable to create StreamExecutor for CUDA:1: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
2019-08-08 15:50:08.858013: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Aborted (core dumped)
"

**Comment by lgeiger** [comment]
This looks like a TensorFlow error unrelated to larq, are you running a second process using TensorFlow?

Could you also try with TensorFlow 1.14.0? We have seen a lot of problems with the beta version of TF 2 in the past, so it might be worth waiting until the release candidate or a stable TF 2 version comes out.

**Comment by appleleaves** [comment]
Using TensorFlow 1.14.0 solves the problem!

**Comment by lgeiger** [comment]
Great!
